# Generated by Django 2.2.1 on 2019-06-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='description',
            new_name='text',
        ),
    ]
